### ISSUE TITLE
Wrong regular expression in 1.0.3

### ISSUE THREAD

**Issue by wyomind** [Sental/db-override#1]
^10\.[2-11]\. is not valid.
Should be something like:
^10\.([2-9]|10|11)\.

**Comment by Sental** [comment]
Thanks for creating the issue. Fixed in the newest release.

**Comment by wyomind** [comment]
-- Please reply above this line --

Hey Sental/db-Override,

Thank you for your message.

 Your request has been correctly submitted.
     
 We’ll be getting back to you as soon as possible!

 Best Regards,
 The Wyomind Team
