### ISSUE TITLE
Add php 8.3 support

### ISSUE THREAD

**Issue by dlabsnl** [Sental/db-override#2]
composer require reessolutions/db-override:*
./composer.json has been updated
Running composer update reessolutions/db-override
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - reessolutions/db-override 1.0.0 requires php ~7.3.0 || ~7.4.0 -> your php version (8.3.10) does not satisfy that requirement.
    - reessolutions/db-override[1.0.1, ..., 1.0.3] require php ~7.2.0 || ~7.3.0 || ~7.4.0 || ~8.1.0 -> your php version (8.3.10) does not satisfy that requirement.
    - reessolutions/db-override[1.0.4, ..., 1.0.6] require php ~7.2.0 || ~7.3.0 || ~7.4.0 || ~8.1.0 || ~8.2.0 -> your php version (8.3.10) does not satisfy that requirement.
    - Root composer.json requires reessolutions/db-override * -> satisfiable by reessolutions/db-override[1.0.0, ..., 1.0.6].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by Sental** [comment]
Fixed in v1.0.7

**Comment by dlabsnl** [comment]
Ty for fast fix!
